---
title: "Will's Favorite Recipes"
author: "Plagiarized From Legion"
date: "`r format(Sys.time(), '%B %Y')`"
abstract: "Here are a bunch of my favorite recipes. They have been plagiarized form my favorite cookbooks, people, websites, etc. Just trying to keep everything in one places. Sources referenced when I can remember them and remember to put them in."
output: 
  pdf_document:
     toc: true
     toc_depth: 2
  html_document:
     theme: darkly
     highlight: tango
     toc: true
     toc_depth: 2
     toc_float: true
     number_sections: false
     keep_md: yes
bibliography: BamLabLib.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
\pagebreak
# Breads

## Sourdough Mother Starter 
[@reinhartPeterReinhartArtisan2009]

### Seed culture 1

* 3.5 tbsp (28.5 g) whole wheat flour
* 1/4 c (56.5 g) pineapple juice

Mix up. Lightly cover. Stir a few times a day for ~48 hours.

### Seed culture 2

* 3.5 tbsp (28.5 g) whole wheat flour
* 2 tbsp (28.5 g) pineapple juice or water
* seed culture 1

Mix. Cover. Stir a few times a day for ~48 hours. If it gets really bubble, jump to stage 3.

### Seed culture 3

* 7 tbsp (56.5 g) whole wheat flour
* 2 tbsp water
* seed culture 2

Mix and knead a bit. New bowl, cover, stir a few times a day for 24-48 hours.

If not bubble, keep going a couple more days.

### Seed culture 4

* 10.5 tbsp (85 g) whole wheat flour
* 2 tbsp water
* seed culture 3 (1/2 c or all)

Mix & knead. Room temperature until doubles in size.

### Mother Starter

* 2.75 c (340 g) whole wheat flour
* 1c + 2 tbsp (255 g) water
* seed culture 4 (half or all)

Mix and knead. Rest at room temp until doubled (4-8 hours). Punch it down, put in good container, and toss in fridge. BOOM, you've got a starter.

\pagebreak
## Pain a l'Ancienne 
[@reinhartPeterReinhartArtisan2009]

* 4.5 c (567 g) flour
* 1.75 tsp (11 g) salt
* 1.25 (4g) yeast
* 2 c (454 g) water
* 1 tbsp oil

1. Mix for a minute or so, until shaggy and sticky. Rest 5 min.
2. Drizzle oil. Mix/knead for a minute. Rest 10 min.
3. Stretch and fold 4x in 40 min.
4. Split and refrigerate overnight-4 days.
5. Remove an hour or two before baking. 
6. After an hour shape into ciabatta or whatevs.
7. Rise another hour. Flip if wanted.
8. Oven 550 F (288 C). Dough in, toss in water, lower to 450 (232).
9. Bake 12, rotate, bake until done (~10-15 min).

\pagebreak
## Pain au Levain
[@reinhartPeterReinhartArtisan2009]

### Starter

* 1/3 c (71 g) mother starter
* 1 c + 2 tbsp (142 g) white flour
* 2/3 c (85 g) whole wheat flour
* 2/3 c (151.5 g) water

1. Mix everything thoroughly. Stir for a couple of minutes. Knead a bit.
2. Rise at room temp for 6-8 hours.

### Dough

* sourdough starter
* 1c + 6 tbsp (312 g) water
* 2.25 tsp (7 g) yeast (for cowards)
* 3.5 c (454 g) white flour
* 2 3/8 tsp (17 g) salt

1. Cut starter into pieces. Mix in water and yeast (if you're a coward) to get everything a  bit combined.
2. Add flour and salt. Mix and knead for 3 minutes to get a tacky and warm ball. Rest 5 min.
3. Knead a few minutes. Rest 10 min.
4. Stretch and fold, 3-4x in about a half hour.
5. Let rise an hour or two, divide and refrigerate.
6. Fridge overnight.
7. Take out ~ 4 hours before baking.
8. Shape after 2 hours. Rise 1-2 more.
9. Preheat to 500 (260). Dough in, toss a cup of water, drop temp to 450 (232).
10. Bake 12 minutes, rotate, give it 15-25 more.

\pagebreak
## San Francisco Sourdough

### Sourdough starter

* 1/4 c (57 g) mother starter
* 1 3/4 c (227 g) flour
* 1/2 c + 2 tbsp (142 g) water

1. Mix everything thoroughly. Stir for a couple of minutes. Knead a bit.
2. Rise at room temp for 6-8 hours.

### Dough

* starter
* 1 3/4 c (397 g) water
* 4 1/2 c (567 g) flour
* 2.5 tsp (18 g) salt
* 2.25 tsp (7 g) yeast for cowards

1. Cut starter into pieces. Mix in water and yeast (if you're a coward) to get everything a  bit combined.
2. Add flour and salt. Mix and knead for 3 minutes to get a tacky and warm ball. Rest 5 min.
3. Knead a few minutes. Rest 10 min.
4. Stretch and fold, 3-4x in about a half hour.
5. Let rise an hour or two, divide and refrigerate.
6. Fridge overnight.
7. Take out ~ 4 hours before baking.
8. Shape after 2 hours. Rise 1-2 more.
9. Preheat to 500 (260). Dough in, toss a cup of water, drop temp to 450 (232).
10. Bake 12 minutes, rotate, give it 15-25 more.

\pagebreak
## Bagels
[@reinhartPeterReinhartArtisan2009]

### Dough

* 1 tbsp (21 g) honey
* 1 tsp (3 g) yeast
* 1 c + 2 tbsp (255 g) water
* 3.5 c (454) flour

1. Mix honey salt yeast water. Let sit a bit.
2. Wets into the flour, mix for 3 minutes. Stiff coarse ball. Let rest 5 minutes.
3. Knead for 4-5 min.
4. Rest/rise for 1 hour.
5. Shape and place on sheet pan. Refrigerate overnight.

### Cooking

* a pot of water
* 1.5 tbsp malt or honey (optional)
* 1 tbsp (14 g) baking soda
* 1 tsp (7g) salt

1. Remove from fridge 90 minutes before baking.
2. Get water boiling. Chuck in powders.
3. Boil bagels in batches. Let rise, flip after a couple of minutes. Drain and put on oiled sheet.
4. Preheat to 500 (260).
5. Bagels in, lower to 450 (230).
6. Bake 8 minutes, rotate. Bake 8-10 more. 

\pagebreak
## Struan
[@reinhartPeterReinhartArtisan2009]

* 5 c (638 g) flour
* 1/4 c (43 g) cornmeal
* 1/4 c (29 g) rolled oats
* 1/2 c (57 g) cooked brown rice
* 1/4 c (57 g) brown sugar
* 2.5 tsp (19 g) salt
* 2 tbsp (19 g) yeast
* 1.5 tbsp (29 g) honey or agave
* 1.5 c (340 g) water
* 1/2 c (113 g) lukewarm buttermilk, yogurt, or other milk
* random ass garnish

1. Combine everything in a big ass bowl. Mix for a couple of minutes.
2. Rest 5 minutes.
3. Knead 2 minutes. Rest. Knead 2 minutes.
4. Stretch and fold with 10 minute rests. 4x in 40 minutes.
5. Divide and refrigerate.
6. Remove from fridge 2 hours before baking. Shape immediately.
7. Preheat 350 (180).
8. Garnish if wanted.
9. Bake 15, rotate. Bake 15 more.

\pagebreak
## English Muffins
[@reinhartPeterReinhartArtisan2009]

* 2 tsp (14 g) honey
* 1 tbsp (14 g) olive oil
* 1.5 c (340 g) milk
* 2.67 c (340 g) flour
* 3/4 tsp (5.5 g) salt
* 2 tsp (6 g) yeast
* 1/4 tsp (2 g) baking soda
* 3 tbsp (43 g) water

1. Combine honey, oil, milk, stir to dissolve.
2. Whisk together dry stuff.
3. Pour wet mix into dry mix. Whisk for a minute or so, into a wet sponge.
4. Cover and refrigerate overnight.
5. Take out 2 hours prior to baking.
6. Right before baking, fold in soda and water mix.
7. Skillet cook on low, 1/3 c at a time, with sprinkled cornmeal.
8. As they cool, stab around edge with a fork so they'll split.

\pagebreak
## Pita
(New York Times)

* 2 teaspoons active dry yeast
* ½ teaspoon sugar
* 35 grams whole-wheat flour (3/4 cup)
* 310 grams unbleached all-purposed flour (2 cups)
* 1 teaspoon kosher salt
* 2 tablespoons olive oil

Directions

1. Make sponge: Put 1 cup lukewarm water in a large mixing bowl. Add yeast and sugar. Stir to dissolve. Add the whole-wheat flour and 1/4 cup all-purpose flour and whisk together. Put bowl in a warm (not hot) place, uncovered, until mixture is frothy and bubbling, about 15 minutes.

2. Add salt, olive oil and nearly all remaining all-purpose flour (reserve 1/2 cup). With a wooden spoon or a pair of chopsticks, stir until mixture forms a shaggy mass. Dust with a little reserved flour, then knead in bowl for 1 minute, incorporating any stray bits of dry dough.

3. Turn dough onto work surface. Knead lightly for 2 minutes, until smooth. Cover and let rest 10 minutes, then knead again for 2 minutes. Try not to add too much reserved flour; the dough should be soft and a bit moist. (At this point, dough may refrigerated in a large zippered plastic bag for several hours or overnight. Bring dough back to room temperature, knead into a ball and proceed with recipe.)

4. Clean the mixing bowl and put dough back in it. Cover bowl tightly with plastic wrap, then cover with a towel. Put bowl in a warm (not hot) place. Leave until dough has doubled in size, about 1 hour.

5. Heat oven to 475 degrees. On bottom shelf of oven, place a heavy-duty baking sheet, large cast-iron pan or ceramic baking tile. Punch down dough and divide into 8 pieces of equal size. Form each piece into a little ball. Place dough balls on work surface, cover with a damp towel and leave for 10 minutes.

6. Remove 1 ball (keeping others covered) and press into a flat diskc with rolling pin. Roll to a 6-inch circle, then to an 8-inch diameter, about 1/8 inch thick, dusting with flour if necessary. (The dough will shrink a bit while baking.)

7. Carefully lift the dough circle and place quickly on hot
baking sheet. After 2 minutes the dough should be nicely puffed. Turn over with tongs or spatula and bake 1 minute more. The pita should be pale, with only a few brown speckles. Transfer warm pita to a napkin-lined basket and cover so bread stays soft. Repeat with the rest of the dough balls.


\pagebreak
# Baking

## Chocolate Chip Cookie, no egg
(BBC good food)

* 125g butter or pure vegetable margarine, softened
* 125g caster sugar
* 1 tsp vanilla essence or extract
* 200g self-raising flour
* 1 tsp baking powder/soda
* 1 tbsp water
* Optional: 2 tbsp coco powder (to make it chocolate)
* Optional : milk chocolate chips or milk chocolate cut into chips or 2 oreos

Directions

1. Preheat the oven to 180°C ,350°F or gas mark 4.

2. Cream the butter and sugar together(with a wooden spoon) in a large bowl until light, fluffy and golden.

3. Stir everything together (vanilla, flour, baking powder and chocolate chips or oreos, add the water and the Coco powder) to make the yummy dough.

4. Sprinkle some flour onto a surface and the dough. Roll out the dough and with cookie cutters cut out the shapes and lay them out onto greased, lined baking sheets. Spacing them well apart.

5. Bake for about 12 minutes or until golden brown.

6. Leave on the baking sheets for 5 minutes, then transfer to a wire rack to cool.

7. Store in an airtight tin for up to 2-3 weeks.

\pagebreak
## Coffee Cake
[@SeriousEatsCoffee2020]

### Topping

* 4 ounces light brown sugar (about 1/2 cup, packed; 115g)
* 2 1/2 ounces whole wheat flour (about 1/2 cup, spooned; 70g)
* 1 tablespoon (5g) ground cinnamon
* 1/4 teaspoon (1g) Diamond Crystal kosher salt; for table salt, use half as much by volume or use the same weight
* Shy 1/4 teaspoon ground cardamom
* 2 ounces unsalted butter (about 4 tablespoons; 55g), soft, about 70°F (21°C)

### Cake

* 14 ounces plain or quick-toasted sugar (2 cups; 395g)
* 6 ounces unsalted butter (about 12 tablespoons; 170g), about 65°F (18°C)
* 4 teaspoons baking powder
* 1 teaspoon (4g) Diamond Crystal kosher salt; for table salt, use half as much by volume or use the same weight
* 1/2 ounce vanilla extract (1 tablespoon; 15g)
* 3 large eggs, brought to about 65°F (about 5 1/4 ounces; 150g), see note
* 12 ounces all-purpose flour, such as Gold Medal (about 2 2/3 cups, spooned; 340g)
* 14 ounces plain Greek yogurt (about 1 3/4 cup; 395g), any percentage will do, brought to about 65°F (see note)

Directions

1. **For the Topping:** In the bowl of a stand mixer fitted with a paddle attachment, combine brown sugar, whole wheat flour, cinnamon, salt, cardamom, and butter. Mix on low speed until sandy and well combined. Scrape onto a large plate or sheet of parchment. Alternatively, the crumb topping can be transferred to an airtight container and refrigerated for up to one week, or frozen for six months. Wipe bowl and paddle with a paper towel and proceed to the next step—no need to wash!

2. **For the Coffee Cake:** Adjust oven rack to lower-middle position and preheat to 350°F (180°C). In the bowl of a stand mixer fitted with a paddle attachment, combine sugar, butter, baking powder, salt, and vanilla. Mix on low to moisten, then increase speed to medium and cream until soft and light, about 10 minutes. Pause to scrape bowl and beater with a flexible spatula, then resume mixing on medium speed. Add eggs one at a time, allowing each to fully incorporate before adding the next.

3. Scrape bowl and beater with a flexible spatula, then resume mixing on low. Sprinkle in about 1/3 of flour, then add 1/3 of Greek yogurt. Repeat with remaining flour and yogurt, working in thirds as before. Fold batter once or twice with a flexible spatula, then scrape into a parchment-lined 9- by 13- by 2-inch anodized-aluminum baking pan. Spread in an even layer, then cover with prepared topping, a handful at a time, squeezing each addition in your palm to help form streusel nuggets.

4. Bake until coffee cake is puffed and firm, about 40 minutes (a toothpick inserted into the center should emerge with a few moist crumbs). Cool cake directly in pan about 30 minutes before serving, as it will be soft and gummy until its crumb has had a chance to set. Cut into squares with a butter knife and lift parchment to help fit an angled spatula under the first slice. To keep coffee cake as fresh as possible, cut only as much as you plan to serve at one time. With plastic wrap or wax paper pressed against cut surface, and top of pan covered with a sheet of aluminum foil, leftovers will keep up to 3 days at room temperature. 

## Earl Grey Blondies
[@prueittTartineClassicRevisited2019]

* 1.5 c (210 g) flour
* 2 tsp/1 bag Earl Grey tea, ground
* 2.25 c (400 g) brown sugar
* 1 c (225 g) melted unsalted butter
* 2 tsp vanilla extract
* 1 tsp salt
* 3 eggs
* caramel sauce
 + 1/2 c (120 g) cream
 + 1 tsp vanilla extract
 + 1 c (200 g) sugar
 + 1 tsp salt
 + 1 tsp lemon juice
 + 2 tbsp (30 g) butter
 
1. Preheat 350 (180). Grease a 9 x 13 tin, with paper.
2. Sift flour and tea
3. Beat together brown sugar, butter, vanilla, and salt.
4. Beat in eggs.
5. Stir in flour.
6. Pour in pan, level. Crisscross pour caramel sauce and pattern.
7. Bake ~ 25 min.
\pagebreak

## Croissant Dough

### Poolish

* 3/4 c (180 g) milk
* 1/2 tsp yeast
* 1.33 c (175 g) flour

1. Slightly warm the milk. Dissolve in yeast.
2. Mix to batter with flour.
3. Rest 2 hours.

### Dough

* 2 tsp yeast
* 1.75 c (420 ml) milk
* 1/3 c (70 g) sugar
* 1 tbsp salt
* 6.25 c (810 g) flour
* 1 tbsp melted butter

1. Mix poolish with yeast.
2. Mix in sugar, salt, half the milk. Scrape down. Add flour.
3. Mix in rest of milk and butter. 
4. Knead a couple minutes.
5. Rest 30 minutes.
6. Knead 7-8 minutes.
7. Press into a rectangle 2 in thick. Bag it.
8. Refrigerate for 6-8 hours.

### Folding

* 2.67 c (600 g) butter, room temperature

1. Put butter between sheets of parchment paper. 
2. Pound butter into 8 x 12 inch rectangle.
3. Flour surface. Roll dough into 12 x 18 inch rectangle.
4. Place butter block in the middle. Fold edges to middle and pinch seal shut. Seal top and bottom seams.
5. Rotate 90 degrees.
6. Roll out to 28 x 12 rectangle. Letter fold in thirds. 
7. Put in bag in refrigerator for a couple of hours.
8. Roll to 28 by 12. Double turn fold (edges to middle, then in half).
9. Bag in freezer for at least 1 hour.
 + can split and store long term at this stage.
 
 \pagebreak
 
## Tartine Morning Buns
[@prueittTartineClassicRevisited2019]

* batch croissant dough
* 1/2 c melted buter
* 1 c brown sugar or sugar
* zest from 2 oranges and a lemon
* 1 tbsp cinnamon
* 1 tsp ginger
* 1 tsp cardamom
* 1 tsp nutmeg, clove, etc.

1. Remove croissant dough from freezer day before. Let it thaw in refrigerator at least overnight.
2. Butter a muffin tin. Rub in some sugar.
3. Mix brown sugar, zests, and spices in a bowl.
4. Roll dough out until 10 x 32 in ch rectangle, horizontal on table.
5. Spread melted butter over dough.
6. Sprinkle and spread sugar mix. Pat it down.
7. Gently roll into tight horizontal roll, the long way.
8. Cut into 12ths. Pop each roll into the muffin tin.
9. Let rise for 2-3 hours. Put muffin tin on a baking sheet for drips.
10. Bake at 400 for 15-30 min, pushing pastries down after about 5-10 minutes.
11. A bit after they're out, make sure to spin each one in the pan so the caramel doesn't firm up too much.
\pagebreak
 

# Pasta

## Fresh Tomato Pasta
[@ruhlmanMichaelRuhlmanPasta]

* 4 ripe tomatoes, large dice
* 1 1/2 to 2 teaspoons coarse kosher salt
* 12 ounces spaghetti or any pasta you like
* 10 cloves of garlic
* 1 cup basil, cut into ribbons
* 3 ounces butter, cut into three chunks
* Olive oil, as needed

1. Season the tomatoes with the salt and toss them well.
2. Put a big pot of water on to boil.
3. Smash the garlic with the flat side of a knife, give it all a few rough chops with the knife and set them a side in a small bowl.
4. Cut the basil into ribbons or roughly chop it. Take a pinch of this basil, chop it finely, and add it to the tomatoes to season the water.
5. Cook your pasta, drain it, put it back in the pot, and oil the pasta to keep it from sticking to itself. (Meanwhile, even if your water isn’t boiling yet, you should still get your garlic cooking in the next step).
6. Heat a teaspoon or two of olive oil in a large sauté pan over medium-high heat, add the garlic and cook it till it is just beginning to brown around the edges and soften, a couple minutes. Give it a pinch of salt if you wish.
7. Pour the tomatoes into a strainer or colander over the garlic so that the tomato water will stream into the pan below. Set the strainer with the tomatoes into the bowl so they don’t drip on the counter, and swirl the sauce to bring it to a simmer. Add the butter while continuing to swirl or stir the sauce. Keep the sauce moving until all the butter is melted. Add the pasta and toss to coat the pasta evenly. Divide the pasta among four bowls and top with the tomatoes and basil.
\pagebreak

# Seafood

# Soups

## Pressure Cooker Pho
[@SeriousEatsDestination]

* 2 tablespoons canola or vegetable oil
* 2 medium yellow onions, split in half
* 1 small hand of ginger, roughly sliced
* 1 small bunch cilantro
* 3 star anise pods
* 1 cinnamon stick
* 4 cloves
* 1 teaspoon fennel seeds
* 1 teaspoon coriander seeds
* 6 to 8 chicken drumsticks
* 1/4 cup fish sauce, plus more to taste
* 2 tablespoons rock sugar or raw sugar, plus more to taste

 1. Heat oil in a pressure cooker over high heat until smoking. Add halved onions and ginger, cut side down. Cook without moving, reducing heat if smoking excessively, until onion and ginger are well charred, about 5 minutes.

2. Add cilantro, star anise, cinnamon, cloves, fennel seed, coriander, and chicken to the pot. Add 2 quarts of water, the fish sauce, and the sugar to the pot. Seal the pressure cooker and bring it to high pressure over high heat. Cook on high pressure for 20 minutes, then shock under cold running water in the sink (or release pressure valve if using an electric pressure cooker).

3. Open pressure cooker. Transfer chicken legs to a plate. Pour broth through a fine mesh strainer into a clean pot and discard solids. Skim any scum off the surface of the broth using a ladle, but leave the small bubbles of fat intact. Season broth to taste with more fish sauce and sugar if desired.

4. To serve, place re-hydrated pho noodles in individual noodle bowls. Top with chicken legs, sliced onions, and scallions. Pour hot broth over chicken and noodles. Serve immediately, allowing guests to add herbs, bean sprouts, chilis, lime, and sauces as they wish.

5. Garnish items: 
+ 1 small white or yellow onion, thinly sliced
+ 1/2 cup thinly sliced scallions
+ 2 cups mixed herbs (cilantro, basil, and mint)
+ 2 cups trimmed bean sprouts
+ Thinly sliced Thai chilis
+ 2 limes, each cut into 4 wedges
+ Hoisin sauce and Sriracha
\pagebreak


\pagebreak
# Plagiarized from...
